#############################################################################
# Makefile for building: 2811_gui
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  2811_gui.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile 2811_gui.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -Wall -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = 2811_gui1.0.0
DISTDIR = /home/kevin/Desktop/ui_coursework_3/.tmp/2811_gui1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lgit2 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = globals.cc \
		main.cc \
		window.cc \
		tabs.cc \
		sc17sdc.cc \
		sc17xc.cc \
		el17dtt.cc \
		el17flc.cc \
<<<<<<< HEAD
		el17oa.cc moc_window.cpp \
		moc_tabs.cpp \
		moc_myFormLayout.cpp
=======
		mainwindow.cpp \
		el17oa.cc moc_tabs.cpp \
		moc_myFormLayout.cpp \
		moc_mainwindow.cpp
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889
OBJECTS       = globals.o \
		main.o \
		window.o \
		tabs.o \
		sc17sdc.o \
		sc17xc.o \
		el17dtt.o \
		el17flc.o \
		mainwindow.o \
		el17oa.o \
		moc_window.o \
		moc_tabs.o \
		moc_myFormLayout.o \
		moc_mainwindow.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		2811_gui.pro window.h \
		tabs.h \
		myFormLayout.h \
		mainwindow.h globals.cc \
		main.cc \
		window.cc \
		tabs.cc \
		sc17sdc.cc \
		sc17xc.cc \
		el17dtt.cc \
		el17flc.cc \
		mainwindow.cpp \
		el17oa.cc
QMAKE_TARGET  = 2811_gui
DESTDIR       = 
TARGET        = 2811_gui


first: all
####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: 2811_gui.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		2811_gui.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile 2811_gui.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
2811_gui.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile 2811_gui.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents window.h tabs.h myFormLayout.h mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents globals.cc main.cc window.cc tabs.cc sc17sdc.cc sc17xc.cc el17dtt.cc el17flc.cc mainwindow.cpp el17oa.cc $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
<<<<<<< HEAD
compiler_moc_header_make_all: moc_window.cpp moc_tabs.cpp moc_myFormLayout.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_window.cpp moc_tabs.cpp moc_myFormLayout.cpp
moc_window.cpp: /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		window.h
	/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I'/home/cserv1_a/elec_ug/el17oa/Desktop/cwk3 ui repo/ui_coursework_3' -I'/home/cserv1_a/elec_ug/el17oa/Desktop/cwk3 ui repo/ui_coursework_3' -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore window.h -o moc_window.cpp

moc_tabs.cpp: /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QDialog \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		tabs.h
	/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I'/home/cserv1_a/elec_ug/el17oa/Desktop/cwk3 ui repo/ui_coursework_3' -I'/home/cserv1_a/elec_ug/el17oa/Desktop/cwk3 ui repo/ui_coursework_3' -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore tabs.h -o moc_tabs.cpp
=======
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -Wall -std=c++11 -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_tabs.cpp moc_myFormLayout.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_tabs.cpp moc_myFormLayout.cpp moc_mainwindow.cpp
moc_tabs.cpp: tabs.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/ui_coursework_3 -I/home/kevin/Desktop/ui_coursework_3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tabs.h -o moc_tabs.cpp
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889

moc_myFormLayout.cpp: gitpp.h \
		trace.h \
		myFormLayout.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/ui_coursework_3 -I/home/kevin/Desktop/ui_coursework_3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include myFormLayout.h -o moc_myFormLayout.cpp

moc_mainwindow.cpp: mainwindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/ui_coursework_3 -I/home/kevin/Desktop/ui_coursework_3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all: sc17xc.moc
compiler_moc_source_clean:
	-$(DEL_FILE) sc17xc.moc
sc17xc.moc: globals.h \
		dispatch.h \
		gitpp.h \
		trace.h \
<<<<<<< HEAD
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLabel \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qframe.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QCheckBox \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qcheckbox.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QStatusBar \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QFormLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qformlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QAbstractButton \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QButtonGroup \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qbuttongroup.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QRadioButton \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qradiobutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QObject \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QSignalMapper \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsignalmapper.h \
		sc17xc.cc
	/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I'/home/cserv1_a/elec_ug/el17oa/Desktop/cwk3 ui repo/ui_coursework_3' -I'/home/cserv1_a/elec_ug/el17oa/Desktop/cwk3 ui repo/ui_coursework_3' -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore sc17xc.cc -o sc17xc.moc
=======
		sc17xc.cc \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/ui_coursework_3 -I/home/kevin/Desktop/ui_coursework_3 -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include sc17xc.cc -o sc17xc.moc
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889

compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

globals.o: globals.cc dispatch.h \
		gitpp.h \
		trace.h \
		globals.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o globals.cc

main.o: main.cc window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

window.o: window.cc window.h \
<<<<<<< HEAD
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		tabs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QDialog \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		globals.h \
		dispatch.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QWidget \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QStatusBar \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QMenuBar \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmenubar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmenu.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qaction.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qactiongroup.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QApplication \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qapplication.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreapplication.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qeventloop.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qguiapplication.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qinputmethod.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QCoreApplication \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QSize \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QDesktopWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cc

tabs.o: tabs.cc tabs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QDialog \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmargins.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpaintdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrect.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsize.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpoint.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpalette.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcolor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qrgb.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qbrush.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvector.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qmatrix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpolygon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qregion.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qline.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtransform.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpainterpath.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qimage.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpixmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qhash.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfont.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontmetrics.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qfontinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qsizepolicy.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qkeysequence.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvariant.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdebug.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtextstream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlocale.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qset.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfile.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfiledevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvector2d.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtouchdevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
=======
		tabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cc

tabs.o: tabs.cc tabs.h \
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889
		globals.h \
		dispatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabs.o tabs.cc

sc17sdc.o: sc17sdc.cc globals.h \
		dispatch.h \
		gitpp.h \
		trace.h \
		window.h \
		myFormLayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sc17sdc.o sc17sdc.cc

sc17xc.o: sc17xc.cc globals.h \
		dispatch.h \
		gitpp.h \
		trace.h \
<<<<<<< HEAD
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLabel \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qframe.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QCheckBox \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qcheckbox.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QStatusBar \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qstatusbar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QFormLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qformlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QAbstractButton \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QButtonGroup \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qbuttongroup.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QRadioButton \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qradiobutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QObject \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QSignalMapper \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsignalmapper.h \
		sc17xc.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sc17xc.o sc17xc.cc

el17dtt.o: el17dtt.cc 
=======
		sc17xc.moc
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sc17xc.o sc17xc.cc

el17dtt.o: el17dtt.cc globals.h \
		dispatch.h \
		mainwindow.h
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o el17dtt.o el17dtt.cc

el17flc.o: el17flc.cc globals.h \
		dispatch.h \
		tabs.h \
<<<<<<< HEAD
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QDialog \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qdialog.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		window.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QMainWindow \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qmainwindow.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qtabwidget.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLabel \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qframe.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QSpinBox \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qspinbox.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractspinbox.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qvalidator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregularexpression.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QVBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QCheckBox \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qcheckbox.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QRadioButton \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qradiobutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QPalette
=======
		window.h
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o el17flc.o el17flc.cc

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

el17oa.o: el17oa.cc globals.h \
		dispatch.h \
		gitpp.h \
<<<<<<< HEAD
		trace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLabel \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlabel.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qframe.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QHBoxLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qboxlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlayoutitem.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qgridlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QFormLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qformlayout.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QDesktopServices \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qdesktopservices.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstandardpaths.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QUrl \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QLineEdit \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qlineedit.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextcursor.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextformat.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qpen.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qtextoption.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QGridLayout \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QPushButton \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qpushbutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractbutton.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qicon.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QIcon \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/QSlider \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qslider.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtWidgets/qabstractslider.h
=======
		trace.h
>>>>>>> 020cc877452b1cb38a90ca542dd08bc7f35bb889
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o el17oa.o el17oa.cc

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_tabs.o: moc_tabs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabs.o moc_tabs.cpp

moc_myFormLayout.o: moc_myFormLayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myFormLayout.o moc_myFormLayout.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

