#############################################################################
# Makefile for building: coursework3_git
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  coursework3_git.pro
# Template: app
# Command: /home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/qmake -o Makefile coursework3_git.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I. -I. -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/cserv1_a/apps/install/qt/5.3.1/5.3/gcc_64 -Wl,-rpath,/home/cserv1_a/apps/install/qt/5.3.1/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib -lQt5Gui -L/home/cserv1_a/apps/install/qt/5.3.1/5.3/gcc_64/lib -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = el17dtt.cc \
		el17flc.cc \
		el17oa.cc \
		globals.cc \
		hci.cc \
		main.cc \
		sc17sdc.cc \
		sc17xc.cc \
		scsfsa.cc \
		tabs.cc \
		window.cc moc_myFormLayout.cpp \
		moc_tabs.cpp
OBJECTS       = el17dtt.o \
		el17flc.o \
		el17oa.o \
		globals.o \
		hci.o \
		main.o \
		sc17sdc.o \
		sc17xc.o \
		scsfsa.o \
		tabs.o \
		window.o \
		moc_myFormLayout.o \
		moc_tabs.o
DIST          = /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		coursework3_git.pro el17dtt.cc \
		el17flc.cc \
		el17oa.cc \
		globals.cc \
		hci.cc \
		main.cc \
		sc17sdc.cc \
		sc17xc.cc \
		scsfsa.cc \
		tabs.cc \
		window.cc
QMAKE_TARGET  = coursework3_git
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = coursework3_git


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: coursework3_git.pro /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/linux.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/qconfig.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resources.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/moc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/lex.prf \
		coursework3_git.pro \
		/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Gui.prl \
		/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile coursework3_git.pro
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/linux.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-base.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/qconfig.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt_config.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/spec_post.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_pre.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/default_post.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/warn_on.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/qt.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/resources.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/moc.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/opengl.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/unix/thread.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/exceptions.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/yacc.prf:
/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/features/lex.prf:
coursework3_git.pro:
/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Gui.prl:
/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile coursework3_git.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/coursework3_git1.0.0 || mkdir -p .tmp/coursework3_git1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/coursework3_git1.0.0/ && $(COPY_FILE) --parents dispatch.h gitpp.h gitpp1.h globals.h hci0.h myFormLayout.h tabs.h trace.h window.h .tmp/coursework3_git1.0.0/ && $(COPY_FILE) --parents el17dtt.cc el17flc.cc el17oa.cc globals.cc hci.cc main.cc sc17sdc.cc sc17xc.cc scsfsa.cc tabs.cc window.cc .tmp/coursework3_git1.0.0/ && (cd `dirname .tmp/coursework3_git1.0.0` && $(TAR) coursework3_git1.0.0.tar coursework3_git1.0.0 && $(COMPRESS) coursework3_git1.0.0.tar) && $(MOVE) `dirname .tmp/coursework3_git1.0.0`/coursework3_git1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/coursework3_git1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_myFormLayout.cpp moc_tabs.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myFormLayout.cpp moc_tabs.cpp
moc_myFormLayout.cpp: gitpp.h \
		trace.h \
		myFormLayout.h
	/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I'/home/cserv1_a/soc_ug/sc17xc/Desktop/year 2/user interface/coursework3_git' -I'/home/cserv1_a/soc_ug/sc17xc/Desktop/year 2/user interface/coursework3_git' -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore myFormLayout.h -o moc_myFormLayout.cpp

moc_tabs.cpp: tabs.h
	/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/bin/moc $(DEFINES) -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/mkspecs/linux-g++ -I'/home/cserv1_a/soc_ug/sc17xc/Desktop/year 2/user interface/coursework3_git' -I'/home/cserv1_a/soc_ug/sc17xc/Desktop/year 2/user interface/coursework3_git' -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui -I/home/csunix/linux/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore tabs.h -o moc_tabs.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

el17dtt.o: el17dtt.cc globals.h \
		dispatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o el17dtt.o el17dtt.cc

el17flc.o: el17flc.cc globals.h \
		dispatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o el17flc.o el17flc.cc

el17oa.o: el17oa.cc globals.h \
		dispatch.h \
		gitpp.h \
		trace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/QDesktopServices \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtGui/qdesktopservices.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstandardpaths.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qalgorithms.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qdatastream.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiodevice.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlist.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qiterator.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcoreevent.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmetatype.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qisenum.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qobject_impl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qpair.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qregexp.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QUrl \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurl.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qurlquery.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qshareddata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o el17oa.o el17oa.cc

globals.o: globals.cc dispatch.h \
		gitpp.h \
		trace.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o globals.cc

hci.o: hci.cc hci0.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hci.o hci.cc

main.o: main.cc window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

sc17sdc.o: sc17sdc.cc globals.h \
		dispatch.h \
		gitpp.h \
		trace.h \
		window.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h \
		myFormLayout.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sc17sdc.o sc17sdc.cc

sc17xc.o: sc17xc.cc globals.h \
		dispatch.h \
		gitpp.h \
		trace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/QString \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstring.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qchar.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobal.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qconfig.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qfeatures.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qtypetraits.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qsysinfo.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qlogging.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qflags.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv7.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv6.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_armv5.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_ia64.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_mips.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_x86.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_gcc.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qatomic_unix.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qmutex.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnumeric.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qbytearray.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qrefcount.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qnamespace.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qarraydata.h \
		/home/cserv1_b/apps/install/qt/5.3.1/5.3/gcc_64/include/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sc17xc.o sc17xc.cc

scsfsa.o: scsfsa.cc 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scsfsa.o scsfsa.cc

tabs.o: tabs.cc tabs.h \
		globals.h \
		dispatch.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tabs.o tabs.cc

window.o: window.cc window.h \
		tabs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cc

moc_myFormLayout.o: moc_myFormLayout.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myFormLayout.o moc_myFormLayout.cpp

moc_tabs.o: moc_tabs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tabs.o moc_tabs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

